#!/usr/bin/perl
#
# This script tabulates observed barcode sequences in an Illumina fastq file.  
# 
# It can be used to determine if there are sample sheet issues, which will cause
# reads with legitimate index sequences (that aren't accurately recorded in the sample sheet)
# to appear in the Undetermine file produced by bcl2fastq
# 
# It expects index sequences to appear in the fastq file in a standard Illumina format, like this:
# @NS500697:346:HJFWTAFX5:1:11101:6998:1049 1:N:0:AGTGGATC+NNGATGAC
# 
# Mark Stenglein 5/18/2023

use strict;

my %bcs = undef;

while (<>)
{
   if (/:([ACGTN\+]{6,21})/)
   {
      $bcs{$1} += 1;
   }
}

foreach my $bc (sort {$bcs{$b} <=> $bcs{$a}} keys %bcs)
{
   print "$bc\t$bcs{$bc}\n";
}

